### ISSUE TITLE
Specify cockroach_connection_string connection_params attributes in docs

### ISSUE THREAD

**Issue by stong88** [cockroachdb/terraform-provider-cockroach#130]
When trying to get just the host uri of a cluster, the most straightforward option seems to be `connection_params` from [`cockroach_connection_string`](https://registry.terraform.io/providers/cockroachdb/cockroach/latest/docs/data-sources/connection_string#connection_params) -- but the documentation only lists `connection_params` as a "map of string" without specifying its attributes. The underlying [cockroach API documentation](https://www.cockroachlabs.com/docs/api/cloud/v1.html#get-/api/v1/clusters/-cluster_id-/connection-string) actually doesn't specify it either, you need to manually call the API to get the parameters.
Can we specify the `connection_params` attributes in the documentation? From calling the cockroach API manually, I got `Database`, `Host`, and `Port`.

**Comment by erademacher** [comment]
Thanks for the suggestion! This has been incorporated with v1.0.0, which is now available.
