### ISSUE TITLE
Support omitted_channels in resource cockroach_log_export_config

### ISSUE THREAD

**Issue by shellderp** [cockroachdb/terraform-provider-cockroach#151]
This API supports `omitted_channels`, it would be nice to support in the provider.  https://www.cockroachlabs.com/docs/api/cloud/v1#delete-/api/v1/clusters/-cluster_id-/logexport

**Comment by marksoper** [comment]
Thanks for posting this Gersh @shellderp - I'm sorry we've been neglecting this. _omitted_channels_ has been added.
