### ISSUE TITLE
Documentation is out of date for dedicated clusters

### ISSUE THREAD

**Issue by aindeev** [cockroachdb/terraform-provider-cockroach#33]
The schema in the documentation at https://registry.terraform.io/providers/cockroachdb/cockroach/latest/docs/data-sources/cluster#nested-schema-for-configdedicated

Does not match how I actually needed to set up my TF configuration:

```
resource "cockroach_cluster" "main" {
  name           = local.cluster_name
  cloud_provider = "GCP"
  create_spec = {
    dedicated = {
      region_nodes  = {
        us-west2 = 3
      }
      hardware = {
        machine_spec = {
          machine_type = "n1-standard-2"
        }
      }
    }
  }
}
```

**Comment by marksoper** [comment]
@aindeev we have made a change to the cluster schema and associated docs. They should be consistent now. Please LMK if you're still seeing a problem.
