### ISSUE TITLE
terraform-registry-manifest.json specifies protocol_versions "5.0" but built binary appears to be "6.0"

### ISSUE THREAD

**Issue by reynoldsme** [cockroachdb/terraform-provider-cockroach#64]
terraform-registry-manifest.json suggests that the supported protocol_version is `5`, but attempting to use the provider in a version of terraform using version `5` (`0.13.7` in this case) reports the following:

```
Failed to instantiate provider "registry.terraform.io/cockroachdb/cockroach"
to obtain schema: Incompatible API version with plugin. Plugin version: 6,
Client versions: [5]
```

Looking at https://developer.hashicorp.com/terraform/registry/providers/publishing#terraform-registry-manifest-file and https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/providerserver#ServeOpts.ProtocolVersion suggests that version 6 will be used unless overridden in ServeOpts.ProtocolVersion which does not appear to be the case: https://github.com/cockroachdb/terraform-provider-cockroach/blob/main/main.go#L53

It would be helpful if terraform 0.13 were supported, but otherwise I imagine protocol_versions should be changed to "6.0" in terraform-registry-manifest.json to avoid any confusion.

Thanks!

**Comment by erademacher** [comment]
This should be fixed with PR #69, which will be included in v0.4.0. Thanks for reporting!
